source /home/danzor/.vim/init/plugins.vimrc
source /home/danzor/.vim/init/singkatan/remap.vimrc
source /home/danzor/.vim/init/set.vimrc
source /home/danzor/.vim/init/prev.vimrc
source /home/danzor/.vim/init/singkatan/command.vimrc
source /home/danzor/.vim/init/singkatan/go.vimrc
source /home/danzor/.vim/init/singkatan/html.vimrc
source /home/danzor/.vim/init/singkatan/css.vimrc
source /home/danzor/.vim/init/singkatan/typos.vimrc
source /home/danzor/.vim/init/singkatan/emoji.vimrc
source /home/danzor/.vim/init/singkatan/md.vimrc
source /home/danzor/.vim/init/singkatan/shell.vimrc
source /home/danzor/.vim/init/singkatan/python.vimrc
source /home/danzor/.vim/init/singkatan/js.vimrc
source /home/danzor/.vim/init/singkatan/jsx.vimrc
source /home/danzor/.vim/init/singkatan/vimrc.vimrc
source /home/danzor/.vim/init/singkatan/global.vimrc
source /home/danzor/.vim/init/highlight.vimrc
